[package]
name = "deboa-ws"
version = "0.1.0-beta.3"
edition = "2021"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa-ws"
homepage = "https://github.com/ararog/deboa"
description = "A friendly rest client on top of hyper."
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["http", "networking", "client", "fetch", "rest-client"]
publish = true
rust-version = "1.85.0"

[features]
default = ["runtime-tokio"]
runtime-tokio = ["dep:tokio", "hyper-util/tokio"]
runtime-smol = ["dep:smol", "dep:smol-hyper"]

[dependencies]
base64 = { version = "0.23.0" }
deboa = { path = "../deboa/deboa" }
#deboa = { version = "0.1.5-beta.2" }
futures-util = { version = "0.3.31", default-features = false }
http = "1"
hyper = { version = "1.11.1", features = ["client"], default-features = false }
hyper-body-utils = { path = "../hyper-body-utils", default-features = false }
#hyper-body-utils = { version = "0.1.17", default-features = false }
hyper-util = { version = "0.1.21", features = [
  "client",
  "client-legacy",
], default-features = false }
pin-project-lite = "0.2.17"
rand = "0.10.3"
smol = { version = "2.0.2", optional = true, default-features = false }
smol-hyper = { version = "0.1.0", optional = true, default-features = false }
thiserror = "2.0.21"
tokio = { version = "1.53.1", optional = true, features = ["io-std"] }
ws-framer = { version = "0.3.2" }
