name: Deboa Unit Tests

permissions:
  contents: read

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test-crates:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run all tests
        run: |
          cargo nextest run --no-fail-fast

  test-deboa:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        runtime: ["smol", "tokio"]
        protocol: ["http1", "http2", "http3"]
        tls: ["native-tls", "rust-tls"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run deboa-${{ matrix.runtime }} tests on ${{ matrix.os }} with ${{ matrix.protocol }} using ${{ matrix.tls }}
        if: (matrix.os != 'windows-latest' && matrix.tls != 'native-tls') || (matrix.os != 'macos-latest' && matrix.tls != 'native-tls')
        run: |
          cd deboa-${{ matrix.runtime }}
          cargo nextest run --no-fail-fast --features "${{ matrix.protocol }} ${{ matrix.tls }} ${{ matrix.tls == 'rust-tls' && 'default-rustls-provider' || '' }} ${{ matrix.tls == 'rust-tls' && 'default-rustls-verifier' || '' }} easyhttpmock-vetis-${{ matrix.runtime }}/${{ matrix.protocol }} easyhttpmock-vetis-${{ matrix.runtime }}/rust-tls" --no-default-features

  build-android:
    runs-on: ubuntu-latest
    container: instrumentisto/cargo-ndk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust toolchains
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build for android archs with cargo-ndk
        run: |
          cd deboa
          cargo ndk --target aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android build
          cd ..

          cd deboa-macros
          cargo ndk --target aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android build
          cd ..
